POST http://localhost:3333/auth/register
Content-Type: application/json

{
  "name": "Luis",
  "email": "luis@gmail.com",
  "password": "password123"
}

###
GET http://localhost:3333/users
Content-Type: application/json
###
GET http://localhost:3333/users/e8161b14-0159-4646-93ec-d42f5b6732bb
Content-Type: application/json

###
POST http://localhost:3333/auth/login
Content-Type: application/json

{
  "email": "luis@gmail.com",
  "password": "password123"
}

###
POST http://localhost:3333/finance/e8161b14-0159-4646-93ec-d42f5b6732bb
Content-Type: application/json

{
  "description": "Venda de produto",
  "type": "s",
  "value": 500
}

###
GET http://localhost:3333/finance/values/e8161b14-0159-4646-93ec-d42f5b6732bb
Content-Type: application/json

###
GET http://localhost:3333/finance/e8161b14-0159-4646-93ec-d42f5b6732bb
Content-Type: application/json

###
GET http://localhost:3333/finance/lucro/e8161b14-0159-4646-93ec-d42f5b6732bb
Content-Type: application/json

###
PUT http://localhost:3333/finance/e8bbf57e-28dd-4493-8797-1c4eb08d9745
Content-Type: application/json

{
  "entrada": 200,
  "saida": 400
}
