POST http://localhost:3333/auth/register
Content-Type: application/json

{
  "name": "Luis",
  "email": "luis@gmail.com",
  "password": "password123"
}

###
GET http://localhost:3333/users
Content-Type: application/json
###
GET http://localhost:3333/users/e8161b14-0159-4646-93ec-d42f5b6732bb
Content-Type: application/json

###
POST http://localhost:3333/auth/login
Content-Type: application/json

{
  "email": "luis@gmail.com",
  "password": "password123"
}

###
POST http://localhost:3333/finance/e8161b14-0159-4646-93ec-d42f5b6732bb
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJiNjQiOnRydWUsInN1YiI6ImU4MTYxYjE0LTAxNTktNDY0Ni05M2VjLWQ0MmY1YjY3MzJiYiJ9.F53nlXqs5h95us7Rxd5m5YCkCFnFkgeei_xZmcB240M

{
  "description": "Venda de mercadorias",
  "type": "s",
  "value": 10500
}

###
GET http://localhost:3333/finance/values/e8161b14-0159-4646-93ec-d42f5b6732bb
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJiNjQiOnRydWUsInN1YiI6ImU4MTYxYjE0LTAxNTktNDY0Ni05M2VjLWQ0MmY1YjY3MzJiYiJ9.F53nlXqs5h95us7Rxd5m5YCkCFnFkgeei_xZmcB240M


###
GET http://localhost:3333/finance/e8161b14-0159-4646-93ec-d42f5b6732bb
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJiNjQiOnRydWUsInN1YiI6ImU4MTYxYjE0LTAxNTktNDY0Ni05M2VjLWQ0MmY1YjY3MzJiYiJ9.F53nlXqs5h95us7Rxd5m5YCkCFnFkgeei_xZmcB240M


###
GET http://localhost:3333/finance/lucro/e8161b14-0159-4646-93ec-d42f5b6732bb
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJiNjQiOnRydWUsInN1YiI6ImU4MTYxYjE0LTAxNTktNDY0Ni05M2VjLWQ0MmY1YjY3MzJiYiJ9.F53nlXqs5h95us7Rxd5m5YCkCFnFkgeei_xZmcB240M


###
PUT http://localhost:3333/finance/e8bbf57e-28dd-4493-8797-1c4eb08d9745
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJiNjQiOnRydWUsInN1YiI6ImU4MTYxYjE0LTAxNTktNDY0Ni05M2VjLWQ0MmY1YjY3MzJiYiJ9.F53nlXqs5h95us7Rxd5m5YCkCFnFkgeei_xZmcB240M

{
  "description": "Venda de mercadorias atualizada",
  "type": "s",
  "value": 2000
}
